services:
  - type: web
    name: shared-expenses-tracker-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
